# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'placar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(331, 530)
        Dialog.setStyleSheet("background-color: white;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 20, 151, 61))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: black;\n"
"    font-size: 19px;\n"
"\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 320, 271, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"    font-size: 20px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-bottom: 2px solid rgb(255, 32, 32);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 61, 61))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: wite;\n"
"    font-family:sans-serif;\n"
"    font-size: 30px;\n"
"    \n"
"    border: none;\n"
"    border-right: 2px solid white;\n"
"    background-color: rgb(234, 115, 53)\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 61, 61))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: wite;\n"
"    font-family:sans-serif;\n"
"    font-size: 30px;\n"
"    \n"
"    border: none;\n"
"    border-left: 2px solid white;\n"
"    background-color: rgb(54, 98, 227)\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "   "))
        self.pushButton_2.setText(_translate("Dialog", "Iniciar"))
